### PR TITLE
finance demo app

### PR DESCRIPTION
**Pull request by DimitriF**

### CODE REVIEW

**Comment by bquast** [comment]
Thanks, this looks good except that the file mode for all files has changed, I'm not sure if that is a good idea. Why is that?

**Comment by DimitriF** [comment]
The function wasn't working, I change it in the last commit.
For the files mode, I put everybody to 777 that's the reason.
I need more experience with git, it's still kind of a mystery how it's working for me.

**Comment by bquast** [comment]
yeah, git is hard. but do you think it is necessary to chmod? otherwise I would rather keep them as they are.

git

**Comment by bquast** [comment]
oh and a small note. usually you end a code file with an empty line, its not imports any more but github starts displaying red things if you dont

http://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-file

**Comment by DimitriF** [comment]
I agree on this one,
Is it possible to close this pull request so I can put my shit together and come back with something cleaner?

**Comment by bquast** [comment]
yeah of course. If I were you I would follow the XKCD advice, just download a fresh copy and copy the files back in

**Pull request closed without merging**
