### PR TITLE
finance demo app

### PR DESCRIPTION
**Pull request by DimitriF**
I hope this one will be better

### CODE REVIEW

**Comment by bquast** [comment]
Great job! Thanks

**Comment by bquast** [comment]
Ok it won't merge because there is an error:

```
0.09schecking examples ... ERROR
Running examples in ‘rnn-Ex.R’ failed
The error most likely occurred in:
> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: run.finance_demo
> ### Title: Demo app on finance data
> ### Aliases: run.finance_demo
> 
> ### ** Examples
> 
> run.finance_demo()
Error in loadNamespace(name) : there is no package called ‘shiny’
Calls: run.finance_demo ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted checking dependencies in R code ... WARNING
'::' or ':::' import not declared from: ‘shiny’ 

```

**Comment by bquast** [comment]
I think all that needs to be added (to `run.finance_demo.R`) is:

    #' @importFrom shiny runApp

**Comment by DimitriF** [comment]
now the shiny package is missing in the description file I think

**Comment by bquast** [comment]
you're right

**Comment by bquast** [comment]
I continued running forever on the last build. I suspect this is the because the `run.finance_demo()` example never ends.

I think that example should be encapsulated by `dontrun()`.

http://stackoverflow.com/questions/12038160/how-to-not-run-an-example-using-roxygen2

**Pull request merged**
